apiVersion: v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka
    spec:
      containers:
      - image: eureka:0.1
        name: eureka
        ports:
        - containerPort: 8761
        resources: {}
        imagePullPolicy: Never
      restartPolicy: OnFailure
status: {}
