apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: hystrix
  name: hystrix
spec:
  ports:
  - name: "7979"
    port: 7979
    targetPort: 7979
  selector:
    app: hystrix
status:
  loadBalancer: {}
