apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-db
  labels:
    app: backup-db
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-db
            image: mongo
            command: ["mongodump","--host", "mongodb:27017"]
            volumeMounts:
            - mountPath: dump
              name: mongodumps
          volumes:
          - name: mongodumps
            persistentVolumeClaim:
              claimName: mongodb-pv-claim
          restartPolicy: OnFailure
