apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service-dply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hystrix
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-service-dply
    spec:
      containers:
      - image: payment-service:0.1
        name: payment
        ports:
        - containerPort: 8004
        resources: {}
        imagePullPolicy: Never
      restartPolicy: OnFailure
status: {}
